# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: go-app
images:
- name: fcoromoto/go-app
  newTag: da2d9f4b254d556040ee15cc6248c4c0d5e0c201
