name: CD

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: fcoromoto
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fcoromoto/go-app
          tags: ${{ github.sha }}, latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: kustomization
        uses: imranismail/setup-kustomize@v1
        with:
            kustomize_version: v3.6.1

      - name: update k8s
        run: |
            kustomize edit set image fcoromoto/go-app:${{ github.sha }}
            cat kustomization.yaml

      - name: commit
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Deploy"
            git commit --am "Atualizando versao da imagem k8s"

      - name: push
        uses: ad-m/github-push-action@master
